# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}

#port options
port-1: 8080
port-2: 8081
port-3: 5433
port-4: 5434

#docker properties
username: ${env.DOCKER_USERNAME}
password: ${env.DOCKER_PASSWORD}
email: ${env.DOCKER_EMAIL}